name: Test

on:
  workflow_dispatch  :
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Display Runner Details
      run: |
        echo "Operating System: $RUNNER_OS"
        echo "Runner Name: $RUNNER_NAME"
        echo "Runner Architecture: $RUNNER_ARCH"
        echo "Image Version:"
        cat /etc/os-release || ver # For Windows runners, `ver` gives OS version
        echo "CPU Info:"
        lscpu || systeminfo | find "Processor" # CPU info for Linux/Windows
        echo "Memory Info:"
        free -h || systeminfo | find "Total Physical Memory" # Memory info for Linux/Windows
        echo "Disk Info:"
        df -h || wmic logicaldisk get size,freespace,caption # Disk info for Linux/Windows
  
    - name: Check packages
      run: |
        python3 --version
        cmake --version
        file "C:\Program Files\CMake\bin\cmake.exe"
        file "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe"    
        file "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com"
        git --version
        file "C:\Program Files\Git\bin\git.exe"
        file "C:\Program Files\Git\bin\bash.EXE" 

    - name: Run Bash Command
      run: |
        echo "Running a Bash command on Windows"
        pwd
      shell: bash

    - name: Call Visual Studio devenv.com
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" /?
      shell: cmd
        
        
